### ISSUE TITLE
Add toggle for SetLaneChangingAllowedWhenGoingStraight flag

### ISSUE THREAD

**Issue by marc2982** [Strdate/AutomaticRoundaboutBuilder#9]
Hi! 

Could we please have a toggle that would allow changing lanes to be set? Normally in my roundabouts I like to set both the traffic on the roundabout and the traffic joining the roundabout to choose their lanes as it seems to help the AI.

Thanks!

**Comment by Strdate** [comment]
I was doing some maintenance work on the mod so on that occasion I implemented this feature. Any feedback is welcome

**Comment by marc2982** [comment]
Thank you! I'll test it as soon as I can :)

**Comment by marc2982** [comment]
Seems to work great, thank you!

I have another request - to be able to set this value differently on the roundabout or the road joining. And the same for crosswalks. Would you like me to open a new issue or keep this one open?

**Comment by Strdate** [comment]
Well, I could have done it in one go if you said.
I am not sure about the crosswalks though - what purpose shall it serve?

Just let this issue open.

**Comment by marc2982** [comment]
Sorry about that, didn't realize I wanted it until I tried it :/

In very busy crosswalks I like to disable all crossings, even around the outside, and build an overpass walkway instead. It helps the cars flow more smoothly.

Thank you!

**Comment by kianzarrin** [comment]
I am against this! `SetLaneChangingAllowedWhenGoingStraight()` does not improve traffic despite Biffa's recommendation. If cars change their lane while entering the roundabout they jam everyone. Better to change lane before arriving at roundabouts so as to reduce jamming.

**Comment by kianzarrin** [comment]
I discussed this with biffa. he didn't seem to have strong opinion: https://github.com/CitiesSkylinesMods/TMPE/issues/793#issuecomment-637627553
> Biffa In your videos you like to enable lane switching at the the entrance of the roundabout:
![image](https://user-images.githubusercontent.com/26344691/83538002-fefe9600-a4fd-11ea-817f-29b2f4b04bd1.png)
as you can see from the image above, if cars lane switch at the roundabout, they are going to get in the way of the cars that are already on the roundabout as well as the cars joining the roundabout on that road.
But if the cars switch lane before arriving at roundabout then they only get in the way of the cars on that road. Which is not a big deal because in on a busy roundabout the cars have to wait before they can enter the roundabout anyway.
![image](https://user-images.githubusercontent.com/26344691/83538553-9ebc2400-a4fe-11ea-86f3-afc8d00de023.png)
When I tried turned on the "Vehicles going straight on may change lanes at junctions" on the roundabout, it had no influence ... probably because cars are not going straight but rather are turning right into the roundabout.
If the highway rules are enabled, its a different story though. If highway rules is enabled (not recommended) and highway roads joins a highway roundabout then you MUST turn on lane switching when entering the roundabout or cars will not use the outer lanes of the roundabout anymore. For this reason my TMPE roundabout auto-setup silently activates the lane changing rule at such circumstances.
>> Biffa27/07/2020: I'll have a think

@marc2982 can you please explain why do you want this feature?

**Comment by marc2982** [comment]
No worries! It looks like you guys have put more thought into this than I have, so if it will not help, no worries.
